[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = '''
cd app & yarn install
'''

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install --all
'''
[[plugins]]
repo = 'junegunn/fzf.vim'
merged = 0

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo= 'sheerun/vim-polyglot'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
