# .zshrc

# 環境変数設定
source ~/dotfiles/zsh/env_variables.zsh

# ヒストリ設定
source ~/dotfiles/zsh/history.zsh

# 補完設定
source ~/dotfiles/zsh/completion.zsh

# エイリアス設定
source ~/dotfiles/zsh/aliases.zsh

# OS別の設定
source ~/dotfiles/zsh/os_specific.zsh

# プロンプト設定
source ~/dotfiles/zsh/prompt.zsh

# その他の設定やカスタマイズ

export PATH=$HOME/.nodebrew/current/bin:$PATH

export PATH=$PATH:/usr/local/texlive/2023/bin/universal-darwin

alias vpn-nishilab='sudo /usr/local/sbin/sstpc --log-stderr --log-level 1 --cert-warn --user minobe --password 10daiki23 nishilab-meeting.vpnazure.net usepeerdns require-mschap-v2 noauth noipdefault defaultroute refuse-eap noccp --tls-ext'

export PATH="/usr/local/sbin:$PATH"

