# .zshrc

# 環境変数設定
source ~/dotfiles/zsh/env_variables.zsh

# ヒストリ設定
source ~/dotfiles/zsh/history.zsh

# 補完設定
source ~/dotfiles/zsh/completion.zsh

# エイリアス設定
source ~/dotfiles/zsh/aliases.zsh

# OS別の設定
source ~/dotfiles/zsh/os_specific.zsh

# プロンプト設定
source ~/dotfiles/zsh/prompt.zsh

# その他の設定やカスタマイズ
# ここに直接.zshrcに追加したい設定や関数を記述

# 特定のプロジェクトやフレームワークに依存する追加設定（例: ROS）
# source /opt/ros/noetic/setup.zsh
# source /home/daiki/catkin_ws/devel/setup.zsh
